using System;using System.IO;using System.Text.Json;using SensCalibr8.Core.Configuration;
namespace SensCalibr8.Services.Configuration
{
 public static class ContinuousCycleContractLoader
 {
  public const string ContractPath="config/continuous-cycle-v1.json";
  public static ContinuousCycleContract LoadFromRepository(string root){string path=Path.Combine(root??string.Empty,ContractPath.Replace('/',Path.DirectorySeparatorChar));if(!File.Exists(path))throw new FileNotFoundException("Continuous-cycle contract was not found.",path);using JsonDocument d=JsonDocument.Parse(File.ReadAllBytes(path));JsonElement r=d.RootElement;Require(r,"schema_version","sc8-continuous-cycle-v1");Require(r,"status","accepted");if(!r.GetProperty("immutable").GetBoolean())throw new InvalidDataException("Continuous-cycle contract must be immutable.");JsonElement t=r.GetProperty("training"),p=r.GetProperty("plateau"),q=r.GetProperty("recalibration");Require(t,"purpose","training");Require(t,"best_source","phase-three-winner-edpi");Require(t,"checkpoint_source","latest-complete-training-battery");Require(p,"comparison","strictly-less-than");Require(p,"zero_baseline_policy","not-plateau");Require(q,"trigger","plateau");Require(q,"new_phase","phase-one");Require(q,"baseline_source","source-phase-three-winner-edpi");return new ContinuousCycleContract(Text(r,"contract_version"),Int(t,"minimum_database_sessions"),Int(t,"maximum_database_sessions"),Int(p,"consecutive_cycles"),Number(p,"relative_score_change_percent"),Number(p,"percentage_scale"),Text(t,"purpose"),Text(q,"generation_rule"));}
  private static void Require(JsonElement e,string n,string x){if(!string.Equals(Text(e,n),x,StringComparison.Ordinal))throw new InvalidDataException("Continuous-cycle contract mismatch: "+n);}private static string Text(JsonElement e,string n){string v=e.GetProperty(n).GetString();return !string.IsNullOrWhiteSpace(v)?v:throw new InvalidDataException("Required contract field is missing: "+n);}private static int Int(JsonElement e,string n)=>e.GetProperty(n).GetInt32();private static double Number(JsonElement e,string n){if(!e.GetProperty(n).TryGetDouble(out double v)||double.IsNaN(v)||double.IsInfinity(v))throw new InvalidDataException("Invalid contract number: "+n);return v;}
 }
}
