using System;

namespace SensCalibr8.Core.Domain
{
    public sealed class MicroCorrectionCaptureEvidence
    {
        public MicroCorrectionCaptureEvidence(long targetId,string targetSize,double targetCenterXpx,double targetCenterYpx,double targetCenterAzimuthDeg,double targetCenterElevationDeg,double initialOffsetDistancePx,double previewTimestampSeconds,double activationTimestampSeconds,double? movementOnsetTimestampSeconds,double resolutionTimestampSeconds,bool isHit,string outcomeReason,double finalAimAzimuthDeg,double finalAimElevationDeg,long? microAdjustmentCount,long? submovementCount,double finalPrecisionErrorDeg,bool isCenterHit,string signalPipelineVersion,bool signalEligible)
        {
            TargetId=targetId>=0?targetId:throw new ArgumentOutOfRangeException(nameof(targetId));TargetSize=Required(targetSize,nameof(targetSize));TargetCenterXpx=Finite(targetCenterXpx,nameof(targetCenterXpx));TargetCenterYpx=Finite(targetCenterYpx,nameof(targetCenterYpx));TargetCenterAzimuthDeg=Finite(targetCenterAzimuthDeg,nameof(targetCenterAzimuthDeg));TargetCenterElevationDeg=Finite(targetCenterElevationDeg,nameof(targetCenterElevationDeg));InitialOffsetDistancePx=NonNegative(initialOffsetDistancePx,nameof(initialOffsetDistancePx));PreviewTimestampSeconds=NonNegative(previewTimestampSeconds,nameof(previewTimestampSeconds));ActivationTimestampSeconds=NonNegative(activationTimestampSeconds,nameof(activationTimestampSeconds));MovementOnsetTimestampSeconds=OptionalNonNegative(movementOnsetTimestampSeconds,nameof(movementOnsetTimestampSeconds));ResolutionTimestampSeconds=NonNegative(resolutionTimestampSeconds,nameof(resolutionTimestampSeconds));IsHit=isHit;OutcomeReason=Required(outcomeReason,nameof(outcomeReason));FinalAimAzimuthDeg=Finite(finalAimAzimuthDeg,nameof(finalAimAzimuthDeg));FinalAimElevationDeg=Finite(finalAimElevationDeg,nameof(finalAimElevationDeg));MicroAdjustmentCount=OptionalNonNegative(microAdjustmentCount,nameof(microAdjustmentCount));SubmovementCount=OptionalNonNegative(submovementCount,nameof(submovementCount));FinalPrecisionErrorDeg=NonNegative(finalPrecisionErrorDeg,nameof(finalPrecisionErrorDeg));IsCenterHit=isCenterHit;SignalPipelineVersion=Required(signalPipelineVersion,nameof(signalPipelineVersion));SignalEligible=signalEligible;
            if(ActivationTimestampSeconds<PreviewTimestampSeconds||ResolutionTimestampSeconds<ActivationTimestampSeconds||MovementOnsetTimestampSeconds.HasValue&&(MovementOnsetTimestampSeconds.Value<ActivationTimestampSeconds||MovementOnsetTimestampSeconds.Value>ResolutionTimestampSeconds))throw new ArgumentException("Micro-Correction timestamps are not ordered.");if(IsHit&&(!SignalEligible||!MicroAdjustmentCount.HasValue||!SubmovementCount.HasValue)||!IsHit&&(MicroAdjustmentCount.HasValue||SubmovementCount.HasValue))throw new ArgumentException("Micro-Correction signal counts do not match the outcome.");
        }
        public long TargetId{get;}public string TargetSize{get;}public double TargetCenterXpx{get;}public double TargetCenterYpx{get;}public double TargetCenterAzimuthDeg{get;}public double TargetCenterElevationDeg{get;}public double InitialOffsetDistancePx{get;}public double PreviewTimestampSeconds{get;}public double ActivationTimestampSeconds{get;}public double? MovementOnsetTimestampSeconds{get;}public double ResolutionTimestampSeconds{get;}public bool IsHit{get;}public string OutcomeReason{get;}public double FinalAimAzimuthDeg{get;}public double FinalAimElevationDeg{get;}public long? MicroAdjustmentCount{get;}public long? SubmovementCount{get;}public double FinalPrecisionErrorDeg{get;}public bool IsCenterHit{get;}public string SignalPipelineVersion{get;}public bool SignalEligible{get;}public double CorrectionTimeSeconds=>ResolutionTimestampSeconds-ActivationTimestampSeconds;
        private static double Finite(double value,string name)=>!double.IsNaN(value)&&!double.IsInfinity(value)?value:throw new ArgumentOutOfRangeException(name);private static double NonNegative(double value,string name)=>Finite(value,name)>=0d?value:throw new ArgumentOutOfRangeException(name);private static double? OptionalNonNegative(double? value,string name)=>value.HasValue?NonNegative(value.Value,name):(double?)null;private static long? OptionalNonNegative(long? value,string name)=>value.HasValue&&value.Value<0?throw new ArgumentOutOfRangeException(name):value;private static string Required(string value,string name)=>!string.IsNullOrWhiteSpace(value)?value:throw new ArgumentException(name+" is required.",name);
    }
}
