using System;using System.Collections.Generic;using System.IO;using System.Linq;using NUnit.Framework;using SensCalibr8.Core.Configuration;using SensCalibr8.Core.Domain;using SensCalibr8.Data.Persistence;using SensCalibr8.Data.Repositories;using SensCalibr8.Services.Calculations;using SensCalibr8.Services.Configuration;using UnityEngine;
namespace SensCalibr8.Tests
{
 public sealed class P5R7ContinuousCycleTests
 {
  private string dir;private SqliteConnectionFactory db;private FrozenCalibrationConfiguration config;private ContinuousCycleContract contract;private ContinuousCycleService service;private ProfileRecord profile;private ProtocolRepository protocol;private long configId;
  [SetUp]public void SetUp(){string root=Root();config=FrozenCalibrationConfigurationLoader.LoadFromRepository(root);contract=ContinuousCycleContractLoader.LoadFromRepository(root);dir=Path.Combine(Path.GetTempPath(),"sc8-p5r7-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);string native=Path.Combine(root,"app","Assets","Plugins","sqlite3.dll");new SqliteDatabaseBootstrapper().Initialize(Path.Combine(dir,"x.sqlite"),config,native);db=new SqliteConnectionFactory(Path.Combine(dir,"x.sqlite"),native);profile=new ProfileRepository(db).Create(new ProfileRecord(null,"p5-r7","2026-07-17",1600,0.175d,1000d,"right","#FFE600","claw","arm",50d,50d,1d,"2026-07-17"));protocol=new ProtocolRepository(db);configId=new CalibrationConfigurationRepository(db).RequireId(config.ConfigVersion.Value);var research=ResearchConstantsLoader.LoadFromRepository(root);var constants=ProtocolConstantsLoader.LoadFromRepository(root);var phaseOne=new PhaseOneExploratoryProtocolService(research,constants,protocol);service=new ContinuousCycleService(new ContinuousCycleRepository(db),contract,phaseOne,new ProfileRepository(db),config);}
  [TearDown]public void TearDown(){if(Directory.Exists(dir))Directory.Delete(dir,true);}
  [Test]public void ContractUsesAcceptedSessionAndPlateauBounds(){Assert.That(contract.MinimumSessions,Is.EqualTo(5));Assert.That(contract.MaximumSessions,Is.EqualTo(10));Assert.That(contract.PlateauCycles,Is.EqualTo(3));Assert.That(contract.PlateauChangePercent,Is.EqualTo(5d));}
  [Test]public void CheckpointRequiresFiveToTenSessionsAndLatestCompleteGrade(){CycleRecord cycle=SeedCycle(1,100d,"A",4);Assert.That(()=>service.FinalizeTraining(profile.Id.Value,cycle.Id.Value,"2026-07-17"),Throws.TypeOf<DataAccessException>());}
  [Test]public void ThreeSameGradeCyclesWithLessThanFivePercentChangeAutoStartPhaseOneAroundBest(){CycleRecord a=SeedCycle(1,100d,"A",5),b=SeedCycle(2,103d,"A",5),c=SeedCycle(3,104d,"A",5);service.FinalizeTraining(profile.Id.Value,a.Id.Value,"2026-07-17");service.FinalizeTraining(profile.Id.Value,b.Id.Value,"2026-07-18");service.FinalizeTraining(profile.Id.Value,c.Id.Value,"2026-07-19");PlateauEvaluation plateau=service.EvaluatePlateau(profile.Id.Value);Assert.That(plateau.Detected,Is.True);Assert.That(plateau.RelativeChangePercent,Is.EqualTo(4d).Within(1e-12));RecalibrationEventRecord result=service.BeginRecalibration(profile.Id.Value,"2026-07-20");using SqliteDatabaseConnection x=db.Open();Assert.That(Scalar(x,"SELECT cycle_number FROM cycles WHERE id="+result.DestinationCycleId+";"),Is.EqualTo(4));Assert.That(Scalar(x,"SELECT COUNT(*) FROM protocol_candidates WHERE cycle_id="+result.DestinationCycleId+" AND phase=1;"),Is.EqualTo(7));Assert.That(Convert.ToDouble(x.Scalar("SELECT anchor_edpi FROM protocol_candidate_sources WHERE candidate_id IN (SELECT id FROM protocol_candidates WHERE cycle_id="+result.DestinationCycleId+") ORDER BY id LIMIT 1;")),Is.EqualTo(280d));Assert.That(()=>service.BeginRecalibration(profile.Id.Value,"2026-07-20"),Throws.TypeOf<DataAccessException>());}
  [Test]public void ExactFivePercentOrGradeChangeDoesNotPlateau(){CycleRecord a=SeedCycle(1,100d,"A",5),b=SeedCycle(2,102d,"A",5),c=SeedCycle(3,105d,"A",5);service.FinalizeTraining(profile.Id.Value,a.Id.Value,"d1");service.FinalizeTraining(profile.Id.Value,b.Id.Value,"d2");service.FinalizeTraining(profile.Id.Value,c.Id.Value,"d3");Assert.That(service.EvaluatePlateau(profile.Id.Value).Detected,Is.False);}
  private CycleRecord SeedCycle(long number,double score,string grade,int sessions){CycleRecord cycle=protocol.CreateCycle(new CycleRecord(null,profile.Id.Value,number,"2026-07-17",null,null));ProtocolCandidateRecord candidate=protocol.CreateCandidateWithSources(new ProtocolCandidateRecord(null,profile.Id.Value,cycle.Id.Value,3,280d,0.175d,"single_anchor","2026-07-17"),new[]{new ProtocolCandidateSourceRecord(280d,0d,280d,false)});new PhaseHistoryRepository(db).Create(new PhaseHistoryRecord(null,profile.Id.Value,cycle.Id.Value,3,280d,"2026-07-17"));ProtocolBatteryRecord first=protocol.CreateBattery(new ProtocolBatteryRecord(null,profile.Id.Value,cycle.Id.Value,candidate.Id.Value,0.175d,3,"training","2026-07-17","2026-07-17"));using(SqliteDatabaseConnection x=db.Open()){for(int i=0;i<Math.Min(sessions,4);i++)x.Execute("INSERT INTO sessions(profile_id,battery_id,calibration_config_id,date,mode,duration_sec,fatigue_flag) VALUES(@p,@b,@c,'d',@m,1,0);",new Dictionary<string,object>{{"@p",profile.Id.Value},{"@b",first.Id.Value},{"@c",configId},{"@m",new[]{"flick_close","flick_far","tracking","micro_correction"}[i]}});if(sessions>=4)x.Execute("INSERT INTO sensitivity_tests(profile_id,cycle_id,calibration_config_id,battery_id,edpi,cm_360,avg_performance_score,performance_score_by_mode,grade,formula_version,phase,sample_size) VALUES(@p,@cy,@c,@b,280,46,@s,'{}',@g,@f,3,1);",new Dictionary<string,object>{{"@p",profile.Id.Value},{"@cy",cycle.Id.Value},{"@c",configId},{"@b",first.Id.Value},{"@s",score},{"@g",grade},{"@f",config.FormulaVersion.Value}});if(sessions>4){ProtocolBatteryRecord second=protocol.CreateBattery(new ProtocolBatteryRecord(null,profile.Id.Value,cycle.Id.Value,candidate.Id.Value,0.175d,3,"training","2026-07-17",null));x.Execute("INSERT INTO sessions(profile_id,battery_id,calibration_config_id,date,mode,duration_sec,fatigue_flag) VALUES(@p,@b,@c,'d','flick_close',1,0);",new Dictionary<string,object>{{"@p",profile.Id.Value},{"@b",second.Id.Value},{"@c",configId}});}}return cycle;}
  private static int Scalar(SqliteDatabaseConnection x,string sql)=>Convert.ToInt32(x.Scalar(sql));private static string Root()=>Path.GetFullPath(Path.Combine(Application.dataPath,"..",".."));
 }
}
