using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.IO;
using System.Text.Json;
using SensCalibr8.Core.Configuration;
using SensCalibr8.Core.Domain;

namespace SensCalibr8.TestLogic
{
    public sealed class FrozenMicroCorrectionContract
    {
        private FrozenMicroCorrectionContract(string version,string signalVersion,double timeout,string targetSize,double minimumOffsetPx,double maximumOffsetPx,double focalLengthPx,double viewportWidthPx,double viewportHeightPx,double targetDiameterDeg,double centerHitRadiusRatio)
        { ModeContractVersion=version;SignalPipelineVersion=signalVersion;ShotTimeoutSeconds=timeout;TargetSize=targetSize;MinimumOffsetPx=minimumOffsetPx;MaximumOffsetPx=maximumOffsetPx;FocalLengthPx=focalLengthPx;ViewportWidthPx=viewportWidthPx;ViewportHeightPx=viewportHeightPx;TargetDiameterDeg=targetDiameterDeg;CenterHitRadiusRatio=centerHitRadiusRatio; }
        public string ModeContractVersion{get;}public string SignalPipelineVersion{get;}public double ShotTimeoutSeconds{get;}public string TargetSize{get;}public double MinimumOffsetPx{get;}public double MaximumOffsetPx{get;}public double FocalLengthPx{get;}public double ViewportWidthPx{get;}public double ViewportHeightPx{get;}public double TargetDiameterDeg{get;}public double CenterHitRadiusRatio{get;}
        public static FrozenMicroCorrectionContract From(FrozenCalibrationConfiguration configuration)
        {
            if(configuration==null)throw new ArgumentNullException(nameof(configuration));try{using JsonDocument modes=JsonDocument.Parse(configuration.Record.TrackingContractJson);using JsonDocument geometry=JsonDocument.Parse(configuration.Record.TargetGeometryJson);JsonElement root=modes.RootElement,micro=root.GetProperty("modes").GetProperty("micro_correction"),geo=geometry.RootElement,geoMicro=geo.GetProperty("micro_correction"),target=geo.GetProperty("target"),viewport=geo.GetProperty("reference_viewport"),camera=geo.GetProperty("camera");string version=root.GetProperty("mode_contract_version").GetString(),size=micro.GetProperty("target_size").GetString();double minimum=micro.GetProperty("offset_px").GetProperty("minimum").GetDouble(),maximum=micro.GetProperty("offset_px").GetProperty("maximum").GetDouble(),timeout=root.GetProperty("shared_shot_contract").GetProperty("trial_timeout_seconds").GetDouble();if(string.IsNullOrWhiteSpace(version)||string.IsNullOrWhiteSpace(size)||timeout<=0d||minimum<=0d||maximum<minimum||minimum!=geoMicro.GetProperty("minimum_center_offset_px").GetDouble()||maximum!=geoMicro.GetProperty("maximum_center_offset_px").GetDouble()||!string.Equals(size,geoMicro.GetProperty("target_size").GetString(),StringComparison.Ordinal)||!string.Equals(micro.GetProperty("activation").GetString(),"center-reference-click-activates-visible-preview-target",StringComparison.Ordinal)||!string.Equals(micro.GetProperty("offset_sampling").GetString(),"deterministic-uniform-radius-and-direction",StringComparison.Ordinal))throw new InvalidDataException("Frozen Micro-Correction contract is unsupported.");return new FrozenMicroCorrectionContract(version,configuration.Record.SignalPipelineVersion,timeout,size,minimum,maximum,camera.GetProperty("reference_focal_length_px").GetDouble(),viewport.GetProperty("width_px").GetDouble(),viewport.GetProperty("height_px").GetDouble(),target.GetProperty("sizes").GetProperty(size).GetProperty("angular_diameter_deg").GetDouble(),target.GetProperty("center_hit_radius_ratio").GetDouble());}catch(JsonException exception){throw new InvalidDataException("Frozen Micro-Correction contract is invalid.",exception);}
        }
    }

    public sealed class MicroCorrectionMode : ITestMode
    {
        private readonly DeterministicTargetSequencer sequencer;private readonly int batteryRepetitionOrdinal;private readonly List<MicroCorrectionCaptureEvidence> resolved=new List<MicroCorrectionCaptureEvidence>();private FrozenMicroCorrectionContract contract;private DeterministicTargetSequence sequence;private PendingOpportunity pending;private int nextConditionIndex;
        public MicroCorrectionMode(DeterministicTargetSequencer sequencer,int batteryRepetitionOrdinal){this.sequencer=sequencer??throw new ArgumentNullException(nameof(sequencer));this.batteryRepetitionOrdinal=batteryRepetitionOrdinal>0?batteryRepetitionOrdinal:throw new ArgumentOutOfRangeException(nameof(batteryRepetitionOrdinal));}
        public TestMode Mode=>TestMode.MicroCorrection;public DeterministicTargetSequence Sequence=>sequence;public TargetCondition CurrentCondition=>pending?.Condition;public IReadOnlyList<MicroCorrectionCaptureEvidence> ResolvedOpportunities=>new ReadOnlyCollection<MicroCorrectionCaptureEvidence>(resolved);
        public void Prepare(EngineSessionContext session,FrozenCalibrationConfiguration configuration){if(session==null)throw new ArgumentNullException(nameof(session));if(session.Mode!=Mode)throw new TestEngineLifecycleException("micro_session_mode_mismatch");contract=FrozenMicroCorrectionContract.From(configuration);sequence=sequencer.Create(new SequenceSeedContext(session.ProfileId,session.Cycle.CycleId,session.Candidate.Phase,Mode,batteryRepetitionOrdinal));if(sequence.Conditions.Count==0)throw new InvalidDataException("Frozen Micro-Correction sequence is incomplete.");foreach(TargetCondition condition in sequence.Conditions){if(condition.Mode!=Mode||condition.TargetSize!=contract.TargetSize||!condition.CenterXpx.HasValue||!condition.CenterYpx.HasValue)throw new InvalidDataException("Frozen Micro-Correction sequence is incomplete.");double offset=Offset(condition);if(offset<contract.MinimumOffsetPx||offset>contract.MaximumOffsetPx)throw new InvalidDataException("Frozen Micro-Correction offset is outside the accepted range.");}Reset();}
        public void Start(){if(sequence==null||contract==null)throw new InvalidOperationException("Micro-Correction must be prepared before start.");Reset();}
        public void Capture(TestModeCaptureEvent value){if(value==null)throw new ArgumentNullException(nameof(value));switch(value.EventType){case "preview_target_visible":Preview(value);break;case "center_reference_activated":Activate(value);break;case "movement_onset":MovementOnset(value);break;case "click":ResolveClick(value);break;case "timeout":ResolveTimeout(value);break;default:throw new TestEngineLifecycleException("micro_unknown_capture_event");}}
        public void CaptureSignal(SubmovementAnalysisResult analysis){RequireActivated();if(analysis==null||!string.Equals(analysis.SignalPipelineVersion,contract.SignalPipelineVersion,StringComparison.Ordinal)||pending.SignalAnalysis!=null)throw new TestEngineLifecycleException("micro_signal_analysis_invalid");pending.SignalAnalysis=analysis;}
        public TestModeCompletion End(){if(pending!=null)return new TestModeCompletion(false,"micro_pending_opportunity");return new TestModeCompletion(resolved.Count==sequence.Conditions.Count,resolved.Count==sequence.Conditions.Count?"micro_complete":"micro_incomplete");}
        public TestModeReport Report(){if(pending!=null||resolved.Count!=sequence.Conditions.Count)throw new TestEngineLifecycleException("micro_report_before_completion");return new TestModeReport("micro-correction-resolved="+resolved.Count.ToString(CultureInfo.InvariantCulture));}
        public void Cancel(string reason){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Cancellation reason is required.",nameof(reason));}public void Recover(string reason){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Recovery reason is required.",nameof(reason));Reset();}
        private void Preview(TestModeCaptureEvent value){if(pending!=null||nextConditionIndex>=sequence.Conditions.Count)throw new TestEngineLifecycleException("micro_preview_invalid");pending=new PendingOpportunity(sequence.Conditions[nextConditionIndex],value.TimestampSeconds);}
        private void Activate(TestModeCaptureEvent value){RequirePending();if(pending.ActivationTimestampSeconds.HasValue||value.TimestampSeconds<pending.PreviewTimestampSeconds)throw new TestEngineLifecycleException("micro_activation_invalid");pending.ActivationTimestampSeconds=value.TimestampSeconds;}
        private void MovementOnset(TestModeCaptureEvent value){RequireActivated();if(pending.MovementOnsetTimestampSeconds.HasValue||value.TimestampSeconds<pending.ActivationTimestampSeconds.Value)throw new TestEngineLifecycleException("micro_movement_onset_invalid");pending.MovementOnsetTimestampSeconds=value.TimestampSeconds;}
        private void ResolveClick(TestModeCaptureEvent value){RequireActivated();if(value.TimestampSeconds<pending.ActivationTimestampSeconds.Value||value.TimestampSeconds-pending.ActivationTimestampSeconds.Value>contract.ShotTimeoutSeconds)throw new TestEngineLifecycleException("micro_click_outside_timeout");bool hit=RequiredBoolean(value,"is_hit");if(hit&&(pending.SignalAnalysis==null||!pending.SignalAnalysis.SignalEligible||!pending.SignalAnalysis.Count.HasValue))throw new TestEngineLifecycleException("micro_hit_requires_eligible_signal");Resolve(value,hit,RequiredDouble(value,"final_aim_azimuth_deg"),RequiredDouble(value,"final_aim_elevation_deg"));}
        private void ResolveTimeout(TestModeCaptureEvent value){RequireActivated();if(value.TimestampSeconds-pending.ActivationTimestampSeconds.Value<contract.ShotTimeoutSeconds)throw new TestEngineLifecycleException("micro_timeout_before_contract_limit");Resolve(value,false,RequiredDouble(value,"final_aim_azimuth_deg"),RequiredDouble(value,"final_aim_elevation_deg"));}
        private void Resolve(TestModeCaptureEvent value,bool hit,double azimuth,double elevation){(double targetAzimuth,double targetElevation)=TargetAngles(pending.Condition);double x=azimuth-targetAzimuth,y=elevation-targetElevation,precision=Math.Sqrt(x*x+y*y),centerRadius=contract.TargetDiameterDeg*contract.CenterHitRadiusRatio/2d;long? count=hit?pending.SignalAnalysis.Count:(long?)null;resolved.Add(new MicroCorrectionCaptureEvidence(pending.Condition.TrialIndex,pending.Condition.TargetSize,pending.Condition.CenterXpx.Value,pending.Condition.CenterYpx.Value,targetAzimuth,targetElevation,Offset(pending.Condition),pending.PreviewTimestampSeconds,pending.ActivationTimestampSeconds.Value,pending.MovementOnsetTimestampSeconds,value.TimestampSeconds,hit,hit?"hit":value.EventType=="timeout"?"timeout":"miss_click",azimuth,elevation,count,count,precision,precision<=centerRadius,contract.SignalPipelineVersion,hit&&pending.SignalAnalysis.SignalEligible));pending=null;nextConditionIndex++;}
        private (double azimuth,double elevation) TargetAngles(TargetCondition condition){double azimuth=Math.Atan((condition.CenterXpx.Value-contract.ViewportWidthPx/2d)/contract.FocalLengthPx)*180d/Math.PI,elevation=Math.Atan((contract.ViewportHeightPx/2d-condition.CenterYpx.Value)/contract.FocalLengthPx)*180d/Math.PI;return(azimuth,elevation);}
        private double Offset(TargetCondition condition){double x=condition.CenterXpx.Value-contract.ViewportWidthPx/2d,y=condition.CenterYpx.Value-contract.ViewportHeightPx/2d;return Math.Sqrt(x*x+y*y);}
        private void RequirePending(){if(pending==null)throw new TestEngineLifecycleException("micro_no_preview_target");}private void RequireActivated(){RequirePending();if(!pending.ActivationTimestampSeconds.HasValue)throw new TestEngineLifecycleException("micro_not_activated");}private void Reset(){resolved.Clear();pending=null;nextConditionIndex=0;}
        private static double RequiredDouble(TestModeCaptureEvent value,string key){if(!value.Metadata.TryGetValue(key,out string text)||!double.TryParse(text,NumberStyles.Float,CultureInfo.InvariantCulture,out double parsed)||double.IsNaN(parsed)||double.IsInfinity(parsed))throw new TestEngineLifecycleException("micro_metadata_"+key+"_invalid");return parsed;}private static bool RequiredBoolean(TestModeCaptureEvent value,string key){if(!value.Metadata.TryGetValue(key,out string text)||!bool.TryParse(text,out bool parsed))throw new TestEngineLifecycleException("micro_metadata_"+key+"_invalid");return parsed;}
        private sealed class PendingOpportunity{public PendingOpportunity(TargetCondition condition,double preview){Condition=condition;PreviewTimestampSeconds=preview;}public TargetCondition Condition{get;}public double PreviewTimestampSeconds{get;}public double? ActivationTimestampSeconds{get;set;}public double? MovementOnsetTimestampSeconds{get;set;}public SubmovementAnalysisResult SignalAnalysis{get;set;}}
    }
}
