using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.IO;
using System.Text.Json;
using SensCalibr8.Core.Configuration;
using SensCalibr8.Core.Domain;

namespace SensCalibr8.TestLogic
{
    public sealed class FrozenTrackingContract
    {
        private FrozenTrackingContract(string version,double duration,double window,int blocks,int adaptationBlocks,IReadOnlyDictionary<string,double> radii,IReadOnlyDictionary<string,string> parameters)
        { ModeContractVersion=version; TrialDurationSeconds=duration; MetricWindowSeconds=window; Blocks=blocks; AdaptationBlocks=adaptationBlocks; TargetRadiiDeg=radii; PathParametersJson=parameters; }
        public string ModeContractVersion { get; } public double TrialDurationSeconds { get; } public double MetricWindowSeconds { get; } public int Blocks { get; } public int AdaptationBlocks { get; } public IReadOnlyDictionary<string,double> TargetRadiiDeg { get; } public IReadOnlyDictionary<string,string> PathParametersJson { get; }
        public static FrozenTrackingContract From(FrozenCalibrationConfiguration configuration)
        {
            if(configuration==null)throw new ArgumentNullException(nameof(configuration));try { using JsonDocument modes=JsonDocument.Parse(configuration.Record.TrackingContractJson);using JsonDocument geometry=JsonDocument.Parse(configuration.Record.TargetGeometryJson);JsonElement root=modes.RootElement,tracking=root.GetProperty("modes").GetProperty("tracking");string version=root.GetProperty("mode_contract_version").GetString();double duration=tracking.GetProperty("trial_duration_seconds").GetDouble(),window=tracking.GetProperty("metric_window_seconds").GetDouble();int blocks=tracking.GetProperty("blocks").GetInt32(),adaptation=tracking.GetProperty("adaptation_blocks").GetInt32();if(string.IsNullOrWhiteSpace(version)||duration<=0d||window<=0d||blocks<=0||adaptation<0||adaptation>=blocks||!string.Equals(tracking.GetProperty("path_evaluation").GetString(),"analytic-from-high-resolution-elapsed-time-not-frame-integrated",StringComparison.Ordinal)||!string.Equals(tracking.GetProperty("window_boundary_policy").GetString(),"clip-sample-intervals-to-six-exact-half-open-one-second-windows",StringComparison.Ordinal))throw new InvalidDataException("Frozen Tracking contract is unsupported.");var radii=new Dictionary<string,double>(StringComparer.Ordinal);foreach(JsonProperty size in geometry.RootElement.GetProperty("target").GetProperty("sizes").EnumerateObject())radii.Add(size.Name,size.Value.GetProperty("angular_diameter_deg").GetDouble()/2d);var paths=new Dictionary<string,string>(StringComparer.Ordinal);foreach(string pattern in Strings(tracking.GetProperty("patterns"))){JsonElement path=tracking.GetProperty(pattern);paths.Add(pattern,path.GetRawText());}if(radii.Count==0||paths.Count==0||duration/window!=Math.Round(duration/window))throw new InvalidDataException("Frozen Tracking contract is incomplete.");return new FrozenTrackingContract(version,duration,window,blocks,adaptation,new ReadOnlyDictionary<string,double>(radii),new ReadOnlyDictionary<string,string>(paths));}catch(JsonException exception){throw new InvalidDataException("Frozen Tracking contract is invalid.",exception);}
        }
        private static IReadOnlyList<string> Strings(JsonElement values){var result=new List<string>();foreach(JsonElement value in values.EnumerateArray())result.Add(value.GetString());return result;}
    }

    public sealed class TrackingMode : ITestMode
    {
        private readonly DeterministicTargetSequencer sequencer; private readonly int batteryRepetitionOrdinal; private readonly List<TrackingCaptureEvidence> resolved=new List<TrackingCaptureEvidence>(); private FrozenTrackingContract contract; private DeterministicTargetSequence sequence; private PendingTrial pending; private int nextConditionIndex;
        public TrackingMode(DeterministicTargetSequencer sequencer,int batteryRepetitionOrdinal){this.sequencer=sequencer??throw new ArgumentNullException(nameof(sequencer));this.batteryRepetitionOrdinal=batteryRepetitionOrdinal>0?batteryRepetitionOrdinal:throw new ArgumentOutOfRangeException(nameof(batteryRepetitionOrdinal));}
        public TestMode Mode=>TestMode.Tracking; public DeterministicTargetSequence Sequence=>sequence; public TargetCondition CurrentCondition=>pending?.Condition; public IReadOnlyList<TrackingCaptureEvidence> ResolvedTrials=>new ReadOnlyCollection<TrackingCaptureEvidence>(resolved);
        public void Prepare(EngineSessionContext session,FrozenCalibrationConfiguration configuration){if(session==null)throw new ArgumentNullException(nameof(session));if(session.Mode!=Mode)throw new TestEngineLifecycleException("tracking_session_mode_mismatch");contract=FrozenTrackingContract.From(configuration);sequence=sequencer.Create(new SequenceSeedContext(session.ProfileId,session.Cycle.CycleId,session.Candidate.Phase,Mode,batteryRepetitionOrdinal));if(sequence.Conditions.Count==0)throw new InvalidDataException("Frozen Tracking sequence is incomplete.");foreach(TargetCondition condition in sequence.Conditions)if(condition.Mode!=Mode||string.IsNullOrWhiteSpace(condition.Pattern)||!contract.TargetRadiiDeg.ContainsKey(condition.TargetSize)||!contract.PathParametersJson.ContainsKey(condition.Pattern))throw new InvalidDataException("Frozen Tracking sequence is incomplete.");Reset();}
        public void Start(){if(sequence==null||contract==null)throw new InvalidOperationException("Tracking must be prepared before start.");Reset();}
        public void Capture(TestModeCaptureEvent value){if(value==null)throw new ArgumentNullException(nameof(value));switch(value.EventType){case "trial_started":StartTrial(value);break;case "aim_sample":Sample(value);break;case "trial_completed":Complete(value);break;default:throw new TestEngineLifecycleException("tracking_unknown_capture_event");}}
        public TestModeCompletion End(){if(pending!=null)return new TestModeCompletion(false,"tracking_pending_trial");return new TestModeCompletion(resolved.Count==sequence.Conditions.Count,resolved.Count==sequence.Conditions.Count?"tracking_complete":"tracking_incomplete");}
        public TestModeReport Report(){if(pending!=null||resolved.Count!=sequence.Conditions.Count)throw new TestEngineLifecycleException("tracking_report_before_completion");return new TestModeReport("tracking-resolved="+resolved.Count.ToString(CultureInfo.InvariantCulture));}
        public void Cancel(string reason){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Cancellation reason is required.",nameof(reason));} public void Recover(string reason){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Recovery reason is required.",nameof(reason));Reset();}
        public TrackingTargetPosition TargetPosition(string pattern,double elapsedSeconds){if(contract==null)throw new InvalidOperationException("Tracking must be prepared before target evaluation.");return Evaluate(pattern,elapsedSeconds,contract.PathParametersJson[pattern]);}
        private void StartTrial(TestModeCaptureEvent value){if(pending!=null||nextConditionIndex>=sequence.Conditions.Count)throw new TestEngineLifecycleException("tracking_trial_start_invalid");pending=new PendingTrial(sequence.Conditions[nextConditionIndex],value.TimestampSeconds);}
        private void Sample(TestModeCaptureEvent value){RequirePending();double elapsed=value.TimestampSeconds-pending.StartSeconds;if(elapsed<0d||elapsed>contract.TrialDurationSeconds||pending.Samples.Count>0&&value.TimestampSeconds<=pending.Samples[pending.Samples.Count-1].TimestampSeconds)throw new TestEngineLifecycleException("tracking_sample_timestamp_invalid");TrackingTargetPosition target=TargetPosition(pending.Condition.Pattern,elapsed);double azimuth=RequiredDouble(value,"aim_azimuth_deg"),elevation=RequiredDouble(value,"aim_elevation_deg"),x=azimuth-target.AzimuthDeg,y=elevation-target.ElevationDeg;pending.Samples.Add(new SamplePoint(value.TimestampSeconds,elapsed,Math.Sqrt(x*x+y*y)));}
        private void Complete(TestModeCaptureEvent value){RequirePending();double elapsed=value.TimestampSeconds-pending.StartSeconds;if(!elapsed.Equals(contract.TrialDurationSeconds))throw new TestEngineLifecycleException("tracking_completion_duration_invalid");if(pending.Samples.Count<2||!pending.Samples[0].ElapsedSeconds.Equals(0d)||!pending.Samples[pending.Samples.Count-1].ElapsedSeconds.Equals(contract.TrialDurationSeconds))throw new TestEngineLifecycleException("tracking_sample_boundaries_invalid");IReadOnlyList<TrackingWindowEvidence> windows=Windows(pending.Samples,contract.TrialDurationSeconds,contract.MetricWindowSeconds,contract.TargetRadiiDeg[pending.Condition.TargetSize]);double onTarget=0d;foreach(TrackingWindowEvidence window in windows)onTarget+=window.TimeOnTargetSeconds;resolved.Add(new TrackingCaptureEvidence(RequiredDouble(value,"sensitivity_value"),pending.Condition.TrialIndex,pending.Condition.BlockIndex,pending.Condition.Pattern,pending.Condition.TargetSize,contract.ModeContractVersion,contract.PathParametersJson[pending.Condition.Pattern],contract.TrialDurationSeconds,DeviationJson(pending.Samples),onTarget,100d*onTarget/contract.TrialDurationSeconds,windows));pending=null;nextConditionIndex++;}
        private static IReadOnlyList<TrackingWindowEvidence> Windows(IReadOnlyList<SamplePoint> samples,double duration,double window,double radius){var output=new List<TrackingWindowEvidence>();int count=checked((int)Math.Round(duration/window));for(int windowIndex=0;windowIndex<count;windowIndex++){double start=windowIndex*window,end=start+window,covered=0d,onTarget=0d,squared=0d;for(int index=0;index<samples.Count-1;index++){double overlap=Math.Max(0d,Math.Min(samples[index+1].ElapsedSeconds,end)-Math.Max(samples[index].ElapsedSeconds,start));if(overlap<=0d)continue;double error=samples[index].RadialErrorDeg;covered+=overlap;squared+=error*error*overlap;if(error<=radius)onTarget+=overlap;}if(!covered.Equals(window))throw new TestEngineLifecycleException("tracking_window_coverage_invalid");output.Add(new TrackingWindowEvidence(windowIndex,start,end,onTarget,100d*onTarget/covered,Math.Sqrt(squared/covered)));}return output.AsReadOnly();}
        private static TrackingTargetPosition Evaluate(string pattern,double t,string parametersJson){if(double.IsNaN(t)||double.IsInfinity(t)||t<0d)throw new ArgumentOutOfRangeException(nameof(t));using JsonDocument document=JsonDocument.Parse(parametersJson);JsonElement value=document.RootElement;if(pattern=="linear"){double range=value.GetProperty("horizontal_half_range_deg").GetDouble(),speed=value.GetProperty("constant_speed_deg_per_sec").GetDouble(),period=value.GetProperty("derived_round_trip_period_seconds").GetDouble(),vertical=value.GetProperty("vertical_offset_deg").GetDouble(),phase=(t%period)/period;return new TrackingTargetPosition(phase<0.5d?-range+2d*range*2d*phase:range-2d*range*2d*(phase-0.5d),vertical);}if(pattern=="curved"){double phase=2d*Math.PI*t/value.GetProperty("period_seconds").GetDouble();return new TrackingTargetPosition(value.GetProperty("horizontal_radius_deg").GetDouble()*Math.Cos(phase),value.GetProperty("vertical_radius_deg").GetDouble()*Math.Sin(phase));}if(pattern=="variable_speed"){double phase=2d*Math.PI*t/value.GetProperty("period_seconds").GetDouble();return new TrackingTargetPosition(value.GetProperty("horizontal_amplitude_deg").GetDouble()*Math.Sin(phase),0d);}throw new TestEngineLifecycleException("tracking_pattern_invalid");}
        private static string DeviationJson(IReadOnlyList<SamplePoint> samples){var values=new List<Dictionary<string,double>>();foreach(SamplePoint sample in samples)values.Add(new Dictionary<string,double>{{"elapsed_seconds",sample.ElapsedSeconds},{"radial_error_deg",sample.RadialErrorDeg}});return JsonSerializer.Serialize(values);}
        private static double RequiredDouble(TestModeCaptureEvent value,string key){if(!value.Metadata.TryGetValue(key,out string text)||!double.TryParse(text,NumberStyles.Float,CultureInfo.InvariantCulture,out double parsed)||double.IsNaN(parsed)||double.IsInfinity(parsed))throw new TestEngineLifecycleException("tracking_metadata_"+key+"_invalid");return parsed;} private void RequirePending(){if(pending==null)throw new TestEngineLifecycleException("tracking_no_active_trial");} private void Reset(){resolved.Clear();pending=null;nextConditionIndex=0;}
        private sealed class PendingTrial { public PendingTrial(TargetCondition condition,double start){Condition=condition;StartSeconds=start;} public TargetCondition Condition{get;}public double StartSeconds{get;}public List<SamplePoint> Samples{get;}=new List<SamplePoint>(); } private sealed class SamplePoint { public SamplePoint(double timestamp,double elapsed,double error){TimestampSeconds=timestamp;ElapsedSeconds=elapsed;RadialErrorDeg=error;}public double TimestampSeconds{get;}public double ElapsedSeconds{get;}public double RadialErrorDeg{get;} }
    }
    public sealed class TrackingTargetPosition { public TrackingTargetPosition(double azimuthDeg,double elevationDeg){AzimuthDeg=azimuthDeg;ElevationDeg=elevationDeg;}public double AzimuthDeg{get;}public double ElevationDeg{get;} }
}
