using System;using System.Collections.Generic;using System.Linq;using SensCalibr8.Core.Configuration;using SensCalibr8.Data.Repositories;
namespace SensCalibr8.Services.Calculations
{
 public sealed class PlateauEvaluation
 {public PlateauEvaluation(bool detected,double? relativeChange,IReadOnlyList<CycleCheckpointRecord> checkpoints){Detected=detected;RelativeChangePercent=relativeChange;Checkpoints=checkpoints;}public bool Detected{get;}public double? RelativeChangePercent{get;}public IReadOnlyList<CycleCheckpointRecord> Checkpoints{get;}}
 public sealed class ContinuousCycleService
 {
  private readonly ContinuousCycleRepository repository;private readonly ContinuousCycleContract contract;private readonly PhaseOneExploratoryProtocolService phaseOne;private readonly ProfileRepository profiles;private readonly FrozenCalibrationConfiguration configuration;
  public ContinuousCycleService(ContinuousCycleRepository repository,ContinuousCycleContract contract,PhaseOneExploratoryProtocolService phaseOne,ProfileRepository profiles,FrozenCalibrationConfiguration configuration){this.repository=repository??throw new ArgumentNullException(nameof(repository));this.contract=contract??throw new ArgumentNullException(nameof(contract));this.phaseOne=phaseOne??throw new ArgumentNullException(nameof(phaseOne));this.profiles=profiles??throw new ArgumentNullException(nameof(profiles));this.configuration=configuration??throw new ArgumentNullException(nameof(configuration));}
  public TrainingCycleState RequireTraining(long profileId,long cycleId)=>repository.RequireTrainingState(profileId,cycleId);
  public ProtocolBatteryRecord StartTrainingBattery(TrainingCycleState state,string date){if(state.SessionCount>=contract.MaximumSessions)throw new InvalidOperationException("The training block already reached its maximum Database Session count.");return repository.CreateTrainingBattery(state,contract.TrainingPurpose,date);}
  public CycleCheckpointRecord FinalizeTraining(long profileId,long cycleId,string date){TrainingCycleState state=RequireTraining(profileId,cycleId);return repository.CreateCheckpoint(state,contract.MinimumSessions,contract.MaximumSessions,contract.Version,date);}
  public PlateauEvaluation EvaluatePlateau(long profileId){IReadOnlyList<CycleCheckpointRecord> all=repository.ListCheckpoints(profileId);if(all.Count<contract.PlateauCycles)return new PlateauEvaluation(false,null,all);CycleCheckpointRecord[] window=all.Skip(all.Count-contract.PlateauCycles).ToArray();if(window.Select(value=>value.FinalGrade).Distinct().Count()!=1)return new PlateauEvaluation(false,null,window);double first=window[0].PerformanceScore,last=window[window.Length-1].PerformanceScore;if(Math.Abs(first)<=configuration.Record.ScoringZeroTolerance)return new PlateauEvaluation(false,null,window);double change=Math.Abs(last-first)/Math.Abs(first)*contract.PercentageScale;return new PlateauEvaluation(change<contract.PlateauChangePercent,change,window);}
  public RecalibrationEventRecord BeginRecalibration(long profileId,string date){PlateauEvaluation plateau=EvaluatePlateau(profileId);if(!plateau.Detected)throw new InvalidOperationException("Plateau conditions are not satisfied.");CycleCheckpointRecord source=plateau.Checkpoints[plateau.Checkpoints.Count-1];TrainingCycleState state=RequireTraining(profileId,source.CycleId);ProfileRecord profile=profiles.FindById(profileId)??throw new InvalidOperationException("Profile is missing.");if(profile.MouseDpi>int.MaxValue)throw new InvalidOperationException("Profile DPI cannot be represented by the Phase 1 contract.");long next=state.CycleNumber+1;IReadOnlyList<ProtocolCandidateCreateRequest> requests=phaseOne.BuildRequests(profileId,source.CycleId,(int)profile.MouseDpi,state.BestEdpi,date);return repository.BeginRecalibration(source,new CycleRecord(null,profileId,next,date,null,"plateau_recalibration_started"),requests,contract.Version,date);}
 }
}
